name: 'PowerDNS Push Documentation Custom Github Action'
description: 'Build mkdocs-style documentation and push to AWS S3 Bucket'
inputs:
  aws_access_key_id:
    description: 'The AWS S3 access key id'
    required: true
  aws_secret_access_key:
    description: 'The AWS S3 secret access key'
    required: true
  aws_region:
    description: 'The AWS region where the bucket is located'
    required: true
  aws_s3_bucket:
    description: 'The name of the S3 bucket used for documentation'
    required: true
  aws_cloudfront_distribution_id:
    description: 'The CloudFront distribution ID (used to invalidate the cache so that the new content is immediately available)'
    required: true
  version_string:
    description: 'The version of the docs. Should be a semver-style version string. Required if version_control is true'
    required: false
  mkdocs_file:
    description: 'The location of the mkdocs.yml file - required if build_docs is true'
    required: false
  bucket_subdir:
    description: 'The sub directory (under bucket_dir) of the documentation bucket to copy the documentation to. Only allowed if bucket_dir is not empty.'
    required: false
  bucket_dir:
    description: 'The directory of the documentation bucket to copy the documentation to'
    required: false
    default: 'docs.powerdns.com'
  build_docs:
    description: 'Whether to build the docs using mkdocs, or just use an existing directory with the built docs in. If false, you must provide docs_dir input'
    required: false
    default: 'true'
  docs_dir:
    description: 'The location of an existing directory containing the built docs to be copied to S3 - required if build_docs is false'
    required: false
  version_control:
    description: 'Whether to create multiple versions of the documentation in subdirectories and a versions.json file at the root. Cannot be true if build_docs is false'
    required: false
    default: 'true'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.aws_access_key_id}}
    - ${{ inputs.aws_secret_access_key}}
    - ${{ inputs.aws_region}}
    - ${{ inputs.aws_s3_bucket}}
    - ${{ inputs.aws_cloudfront_distribution_id}}
    - ${{ inputs.mkdocs_file}}
    - ${{ inputs.version_string}}
    - ${{ inputs.bucket_subdir}}
    - ${{ inputs.bucket_dir}}
    - ${{ inputs.build_docs}}
    - ${{ inputs.docs_dir}}
    - ${{ inputs.version_control}}
